### ISSUE TITLE
HTTP Error 403.14 when debugging with Visual Studio 2017 Community 15.7.1

### ISSUE THREAD

**Issue by leniel** [Breeze/temphire.angular#15]
Cloned the repo and restored all the packages.

The app builds successfully but when it tries to load, Chrome browser shows:

HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory.

Most likely causes:
A default document is not configured for the requested URL, and directory browsing is not enabled on the server.

Things you can try:
If you do not want to enable directory browsing, ensure that a default document is configured and that the file exists.
Enable directory browsing.
Go to the IIS Express install directory.
Run appcmd set config /section:system.webServer/directoryBrowse /enabled:true to enable directory browsing at the server level.
Run appcmd set config ["SITE_NAME"] /section:system.webServer/directoryBrowse /enabled:true to enable directory browsing at the site level.
Verify that the configuration/system.webServer/directoryBrowse@enabled attribute is set to true in the site or application configuration file.

**Comment by marcelgood** [comment]
Are you running the Node or .NET version? What URL is Chrome trying to load?

**Comment by leniel** [comment]
It tries to load http://localhost:49795/ with IIS 10.0.

**Comment by marcelgood** [comment]
The .NET version is using IIS Express unless you changed it. But as far as IIS Express is concerned you may need to create the virtual directory manually. Right-click on the TempHire project, select Properties, then Web and click 'Create Virtual Directory' next to the URL.

As for the Node version, please follow the instructions in the readme exactly. You were supposed to install gulp globally with `npm install gulp -g`, but you installed it locally. You missed `-g`. You also need to run Node 8 and Npm 5. Please verify that you have all the correct versions and that you followed the steps in the readme.

I can't reproduce these issues. I just cloned the repo fresh and it builds and runs fine.

**Comment by leniel** [comment]
I did as you described in Visual Studio. Created the Virtual Directory successfully. However, when trying the URL: http://localhost:49795/ it still shows HTTP Error 403.14 - Forbidden.

These are the tooling versions I have installed:

```
PS C:\Repos\temphire.angular> npm -v
6.0.1
PS C:\Repos\temphire.angular> node -v
v10.1.0
PS C:\Repos\temphire.angular> gulp -v
[03:13:56] CLI version 3.9.1
[03:13:56] Local version 3.9.1
```

In Visual Studio Code I retried with `npm install gulp -g` and I got errors yet:

```
PS C:\Repos\temphire.angular> npm install gulp -g
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.3: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
C:\Users\leniel\AppData\Roaming\npm\gulp -> C:\Users\leniel\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
+ gulp@3.9.1
updated 1 package in 10.089s
PS C:\Repos\temphire.angular> gulp
[03:08:41] Using gulpfile C:\Repos\temphire.angular\gulpfile.js
[03:08:41] Starting 'server-install'...
[03:08:41] Starting 'client-install'...

> sqlite3@3.1.13 install C:\Repos\temphire.angular\Express\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v64-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@10.1.0 (node-v64 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microso
ft Visual Studio 2005 or 3) add the location of the component to the system path if it is installed elsewhere.  [C:\Repos\temphire.angular\Express\nod
e_modules\sqlite3\build\binding.sln]
gyp ERR! build error \ extract:nan: sill extract nan@2.8.0 extracted to C:\Repos\temphire.angular\TempHire\node_modules\.staging\nan-cb9e42b9 (350ms)
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\leniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp [          ........] \ extract:nan: sill extract nan@2.8.0 extracted to C:\Repos\temphire.angular\TempHire\node_modules\.staging\nan-cb9e42b9 (350mERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command[          ........] \ extract:nan: sill extract nan@2.8.0 extracted to C:\Repos\temphire.angular\TempHire\node_modules\.staging\nan-cb "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\leniel\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
"--fallback-to-build" "--module=C:\\Repos\\temphire.angular\\Express\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Repos\\temphire.angular\\Express\\node_modules\\sqlite3\\lib\\binding\\node-v64-win32-x64"
gyp ERR! cwd C:\Repos\temphire.angular\Express\node_modules\sqlite3
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\leniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Repos\temphire.angular\Express\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Repos\temphire.angular\Express\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Repos\temphire.angular\Express\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:957:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
node-pre-gyp [          ........] \ extract:nan: sill extract nan@2.8.0 extracted to C:\Repos\temphire.angular\TempHire\node_modules\.staging\nan-cb9e4ERR! System Windows_NT 10.0.17134
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Repos\\temphire.angular\\Express\\node_modules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Repos\temphire.angular\Express\node_modules\sqlite3
node-pre-gyp ERR! node -v v10.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.38
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\leniel\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Repos\temphire.angular\Express\node_modules\sqlite3\lib\binding\node-v64-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Repos\temphire.angular\Express\node_modules\sqlite3\lib\binding\node-v64-win32-x64' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`Repos\temphire.angular\TempHire\node_modules\.staging\nan-cb9e42b9 (350ms)
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\leniel\AppData\Roaming\npm-cache\_logs\2018-05-16T06_09_08_395Z-debug.log
[03:09:08] [          ........] - extract:nan: sill extract nan@2.8.0 extracted to C:\Repos\temphire.angular\TempHire\node_modules\.staging\nan-cb9e42b"npm" exited with non-zero code 1 , run `npm install` manually
[03:09:08] 'server-install' errored after 27 s
[03:09:08] Error: "npm" exited with non-zero code 1
    at ChildProcess.cmd.on.code (C:\Repos\temphire.angular\node_modules\gulp-install\lib\command-runner.js:14:25)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 31.366s
[!] 50 vulnerabilities found [18878 packages audited]
    Severity: 16 Low | 24 Moderate | 10 High
    Run `npm audit` for more detail


┌─────────────────────────────────────────────────────────────┐
│                   npm update check failed                   │
│             Try running with sudo or get access             │
│            to the local update config store via             │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\leniel\.config │
└─────────────────────────────────────────────────────────────┘
[03:09:15] Finished 'client-install' after 35 s
```

**Comment by leniel** [comment]
I installed nvm to be able to have multiple versions of Node. Got 8.11.2 and the problem still persists in Visual Studio. :|

These are the tooling versions now:

```
PS C:\Users\leniel> npm -v
5.6.0
PS C:\Users\leniel> node -v
v8.11.2
PS C:\Users\leniel> gulp -v
[10:34:09] CLI version 3.9.1
```

**Comment by leniel** [comment]
In Visual Studio Code things went better:

```
PS C:\Repos\temphire.angular> gulp
[10:46:15] Using gulpfile C:\Repos\temphire.angular\gulpfile.js
[10:46:15] Starting 'server-install'...
[10:46:15] Starting 'client-install'...

> sqlite3@3.1.13 install C:\Repos\temphire.angular\Express\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "C:\Repos\temphire.angular\Express\node_modules\sqlite3\lib\binding\node-v57-win32-x64\node_sqlite3.node" is installed via remote
added 114 packages in 26.377s
[10:46:45] Finished 'server-install' after 30 snstall loadAllDepsIntoIdealTree
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 53.122s
[10:47:11] Finished 'client-install' after 56 s
[10:47:11] Starting 'client-build'...
[10:47:24] Using gulpfile C:\Repos\temphire.angular\TempHire\gulpfile.js
[10:47:24] Starting 'build'...

> temphire-angular@1.0.0 build:prod C:\Repos\temphire.angular\TempHire
> webpack --config webpack.prod.js --progress --profile --colors --display-error-details --display-cached

clean-webpack-plugin: C:\Repos\temphire.angular\TempHire\dist\*.* has been removed.
5454ms building modules
51ms finish module graph
4ms sealing
6ms basic dependencies optimization
29ms dependencies optimization
3ms advanced dependencies optimization
28ms after dependencies optimization
1ms optimizing
1ms basic module optimization
2ms module optimization
62ms advanced module optimization
2ms after module optimization
3ms basic chunk optimization
2ms chunk optimization
31ms advanced chunk optimization
21ms after chunk optimization
23ms module and chunk tree optimization
4ms after module and chunk tree optimization
20ms basic chunk modules optimization
288ms chunk modules optimization
5ms advanced chunk modules optimization
3ms after chunk modules optimization
1ms module reviving
4ms module order optimization
1ms advanced module order optimization
1ms before module ids
3ms module ids
3ms module id optimization
1ms chunk reviving
2ms chunk order optimization
3ms before chunk ids
4ms chunk id optimization
7ms after chunk id optimization
3ms record modules
2ms record chunks
129ms hashing
1ms after hashing
2ms record hash
5ms module assets processing
721ms chunk assets processing
3ms additional chunk assets processing
1ms recording
2ms additional asset processing
29936ms chunk asset optimization
3107ms after chunk asset optimization
12ms asset optimization
6ms after asset optimization
4ms after seal
466ms emitting
Hash: 86ef2e5c8ba22305c097
Version: webpack 4.8.2
Time: 60214ms
Built at: 2018-05-16 10:48:50
                             Asset      Size  Chunks                    Chunk Names
    vendor.86ef2e5c8ba22305c097.js   644 KiB       0  [emitted]  [big]  vendor
       app.86ef2e5c8ba22305c097.js  74.5 KiB       1  [emitted]         app
vendor.86ef2e5c8ba22305c097.js.map  3.21 MiB       0  [emitted]         vendor
   app.86ef2e5c8ba22305c097.js.map   139 KiB       1  [emitted]         app
                     ../index.html  1.31 KiB          [emitted]
Entrypoint app [big] = vendor.86ef2e5c8ba22305c097.js vendor.86ef2e5c8ba22305c097.js.map app.86ef2e5c8ba22305c097.js app.86ef2e5c8ba22305c097.js.map
 [2] ./node_modules/@angular/forms/fesm5/forms.js + 1 modules 241 KiB {0} [built]
     |    2 modules
 [3] ./node_modules/@angular/router/fesm5/router.js + 8 modules 239 KiB {0} [built]
     |    9 modules
 [8] ./node_modules/rxjs/_esm5/internal/observable/of.js + 1 modules 1.17 KiB {0} [built]
     |    2 modules
[10] ./node_modules/rxjs/_esm5/internal/Observable.js + 1 modules 13.2 KiB {0} [built]
     |    2 modules
[12] ./node_modules/rxjs/_esm5/internal/observable/from.js + 5 modules 6.33 KiB {0} [built]
     |    6 modules
[14] ./node_modules/rxjs/_esm5/internal/Subscription.js + 3 modules 9.5 KiB {0} [built]
     |    4 modules
[18] ./node_modules/rxjs/_esm5/internal/Subject.js + 1 modules 6.87 KiB {0} [built]
     |    2 modules
[50] ./node_modules/rxjs/_esm5/internal/util/subscribeToResult.js + 1 modules 1.56 KiB {0} [built]
     |    2 modules
[66] ./$$_lazy_route_resource lazy namespace object 160 bytes {1} [built]
     [] 19515ms -> [] 1235ms -> [0] 2384ms -> factory:1185ms building:273ms = 24592ms
[67] (webpack)/buildin/global.js 509 bytes {0} [built]
     [] 19515ms -> [] 1235ms -> [0] 2384ms -> factory:1185ms building:273ms = 24592ms
[70] ./node_modules/lodash-es/remove.js + 5 modules 4.35 KiB {0} [built]
     |    6 modules
[71] ./node_modules/lodash-es/includes.js + 10 modules 9.08 KiB {0} [built]
     |    11 modules
[72] ./node_modules/lodash-es/_baseIteratee.js + 41 modules 34.1 KiB {0} [built]
     |    42 modules
[90] ./app/main.ts + 53 modules 151 KiB {1} [built]
     | ./app/home.component.ngfactory.js 1.97 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/main.ts 231 bytes [built]
     |     factory:19500ms building:15ms = 19515ms
     | ./app/app.module.ts 128 bytes [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/resourcemgt/resource-mgt.module.ts 160 bytes [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/core/core.module.ts 227 bytes [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/shared/shared.module.ts 140 bytes [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/app.component.ngfactory.js 2.14 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/app.module.ngfactory.js 9.36 KiB [built]
     |     [] 19515ms -> factory:1064ms building:171ms dependencies:1022ms = 21772ms
     | ./app/home.component.ts 178 bytes [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/login.component.ngfactory.js 7.53 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/login.component.ts 1.28 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/resourcemgt/resource-detail.component.ngfactory.js 11.6 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/resourcemgt/resource-detail.component.ts 4.85 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/resourcemgt/resource-mgt.component.ngfactory.js 6.63 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     | ./app/resourcemgt/resource-mgt.component.ts 2.68 KiB [built]
     |     [] 19515ms -> [] 1235ms -> factory:1110ms building:1274ms dependencies:2280ms = 25414ms
     |     + 39 hidden modules
[95] ./node_modules/rxjs/_esm5/internal/operators/share.js + 3 modules 13.4 KiB {0} [built]
     |    4 modules
    + 211 hidden modules

WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./app/app.module.ngfactory.js 5560:15-36 7:0-36 37:25-32 37:89-96 37:98-105 37:111-138 37:140-175 37:341-368 37:371-385 37:389-396 37:403-415 37:417-449 37:456-468 37:473-480 37:532-544 37:591-598 37:605-614 37:616-648 37:655-662 37:669-687 37:689-721 37:728-735 37:742-760 37:762-794 37:801-808 37:906-913 37:920-932 37:960-967 37:1029-1036 37:1259-1268 37:1322-1333 37:1337-1344 37:1412-1421 37:1425-1432 37:1507-1514 37:1616-1623 37:1630-1649 37:1685-1692 37:1755-1762 37:1769-1783 37:1785-1799 37:1802-1811 37:1815-1822 37:1863-1870 37:1913-1920 37:2011-2025 37:2071-2078 37:2242-2249 37:2360-2367 37:2453-2460 37:2520-2527 37:2593-2600 37:2660-2667 37:2769-2776 37:2822-2829 37:2898-2905 37:2996-3003 37:3084-3091 37:3139-3146 37:3204-3211 37:3275-3299 37:3301-3312 37:3314-3325 37:3353-3360 37:3418-3425 37:3537-3544 37:3551-3576 37:3641-3648 37:3743-3750 37:3824-3831 37:3896-3903 37:3956-3963 37:4046-4057 37:4061-4068 37:4126-4133 37:4233-4240 37:4292-4299 37:4348-4355 37:4419-4426 37:4433-4448 37:4506-4513 37:4520-4535 37:4609-4616 37:4701-4712 37:4716-4723 37:4730-4748 37:4900-4915 37:4959-4966 37:4972-4996 37:4998-5022 37:5029-5047 37:5052-5059 37:5068-5085 37:5087-5104 37:5107-5116 37:5118-5129 37:5131-5142 37:5144-5159 37:5161-5188 37:5190-5214 37:5218-5225 37:5238-5258 37:5260-5280 37:5283-5300 37:5304-5311 37:5386-5393 37:5463-5470
37:5532-5539 37:5633-5640 37:5692-5699 37:5804-5811 37:5867-5874 37:5941-5948 37:6025-6032 37:6172-6179 37:6235-6242 37:6248-6259 37:6261-6272 37:6279-6286 37:6292-6316 37:6318-6343 37:6346-6357 37:6363-6394 37:6399-6406 37:6944-6951 37:7010-7027 37:7089-7100 37:7102-7126 37:7128-7139 37:7240-7247 37:7360-7367 37:7421-7428 37:7478-7485 37:7549-7556 37:7602-7609 37:7615-7627 37:7640-7647 37:7714-7721
 @ ./app/main.ts

WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./app/app.module.ngfactory.js 5572:15-102 7:0-36 37:25-32 37:89-96 37:98-105 37:111-138 37:140-175 37:341-368 37:371-385 37:389-396 37:403-415 37:417-449 37:456-468 37:473-480 37:532-544 37:591-598 37:605-614 37:616-648 37:655-662 37:669-687 37:689-721 37:728-735 37:742-760 37:762-794 37:801-808 37:906-913 37:920-932 37:960-967 37:1029-1036 37:1259-1268 37:1322-1333 37:1337-1344 37:1412-1421 37:1425-1432 37:1507-1514 37:1616-1623 37:1630-1649 37:1685-1692 37:1755-1762 37:1769-1783 37:1785-1799 37:1802-1811 37:1815-1822 37:1863-1870 37:1913-1920 37:2011-2025 37:2071-2078 37:2242-2249 37:2360-2367 37:2453-2460 37:2520-2527 37:2593-2600 37:2660-2667 37:2769-2776 37:2822-2829 37:2898-2905 37:2996-3003 37:3084-3091 37:3139-3146 37:3204-3211 37:3275-3299 37:3301-3312 37:3314-3325 37:3353-3360 37:3418-3425 37:3537-3544 37:3551-3576 37:3641-3648 37:3743-3750 37:3824-3831 37:3896-3903 37:3956-3963 37:4046-4057 37:4061-4068 37:4126-4133 37:4233-4240 37:4292-4299 37:4348-4355 37:4419-4426 37:4433-4448 37:4506-4513 37:4520-4535 37:4609-4616 37:4701-4712 37:4716-4723 37:4730-4748 37:4900-4915 37:4959-4966 37:4972-4996 37:4998-5022 37:5029-5047 37:5052-5059 37:5068-5085 37:5087-5104 37:5107-5116 37:5118-5129 37:5131-5142 37:5144-5159 37:5161-5188 37:5190-5214 37:5218-5225 37:5238-5258 37:5260-5280 37:5283-5300 37:5304-5311 37:5386-5393 37:5463-5470 37:5532-5539 37:5633-5640 37:5692-5699 37:5804-5811 37:5867-5874 37:5941-5948 37:6025-6032 37:6172-6179 37:6235-6242 37:6248-6259 37:6261-6272 37:6279-6286 37:6292-6316 37:6318-6343 37:6346-6357 37:6363-6394 37:6399-6406 37:6944-6951 37:7010-7027 37:7089-7100 37:7102-7126 37:7128-7139 37:7240-7247 37:7360-7367 37:7421-7428 37:7478-7485 37:7549-7556 37:7602-7609 37:7615-7627 37:7640-7647 37:7714-7721
 @ ./app/main.ts

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable
defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  vendor.86ef2e5c8ba22305c097.js (644 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (719 KiB)
      vendor.86ef2e5c8ba22305c097.js
      app.86ef2e5c8ba22305c097.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
Child html-webpack-plugin for "..\index.html":
     1 asset
    Entrypoint undefined = ../index.html
    [0] (webpack)/buildin/module.js 519 bytes {0} [built]
        [3] 10751ms -> [2] 488ms -> factory:8265ms building:33ms = 19537ms
    [1] (webpack)/buildin/global.js 509 bytes {0} [built]
        [3] 10751ms -> [2] 488ms -> factory:8265ms building:33ms = 19537ms
    [3] ./node_modules/html-webpack-plugin/lib/loader.js!./index.ejs 1.41 KiB {0} [built]
        factory:10633ms building:118ms = 10751ms
        + 1 hidden module
[10:48:51] Finished 'build' after 1.43 min
[10:48:51] Starting 'default'...
[10:48:51] Finished 'default' after 85 μs
[10:48:51] Finished 'client-build' after 1.62 min
[10:48:51] Starting 'run'...
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules\sequelize\lib\sequelize.js:242:13
Listening on port 3000
```

**Comment by marcelgood** [comment]
Ok, so looks like the Node version is running. Not sure what's hosed up with IIS Express. Haven't run into this issue with this app. Is it building fine? Any errors in the Task Runner Explorer. Do you have a hidden .vs folder under TempHire? If so delete it. That's usually where the IIS Express config ends up being stored.

**Comment by leniel** [comment]
Yep. Builds fine. No errors. I gave up on Visual Studio. I'm using Visual Studio Code for now.

How to debug the code using Visual Studio Code?

Right now I'm doing `node server` in the Express directory. I'd like to place a breakpoint in the JavaScript code and see the debugger stopping there.

**Comment by marcelgood** [comment]
That I leave up to you to figure out. Google is your friend. Here's a starting point from a 2 second Google search.

https://code.visualstudio.com/docs/nodejs/nodejs-debugging

**Comment by leniel** [comment]
I was able to debug the code using this guide:

[Using Angular in VS Code](https://code.visualstudio.com/docs/nodejs/angular-tutorial#_debugging-angular)

**Comment by jradxl** [comment]
@leniel
Would you mind writing up what the solution is, as I have found same  using Visual Studio 19, in spite of it building fine.

**Comment by leniel** [comment]
@jradxl: I used Visual Studio Code instead of the full Visual Studio.

**Comment by ConfigAM** [comment]
Hi Leniel, I am getting the same error due to usage of VS 2017, I am migrating webservice from older VS 2008 and the first time I started it works. First if I change .NET to 4.6.1 this error appears. So I believe during debug start a cached IIS was created which must be defined in a web.config file where all parameters must be set.  So now I am searching for the parameter to enable directory browsing.

**Comment by fkhan698** [comment]
I am running into this issue with Visual Studio 2019. In Visual Studio 2017 I don't get a 403 error however. I am running it using IIS and I went into my IIS Manager and enabled directory browsing, but still getting the same 403 error
